version: '3'

services:
  catalog-database:
    container_name: catalog_database
    image: postgres
    restart: always
    ports:
      - "5430:5432"

    environment:
      POSTGRES_USER: ${RINA_PROJECT_DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${RINA_PROJECT_DATABASE_PASSWORD}
      POSTGRES_DB: ${RINA_PROJECT_DATABASE_NAME}

  catalog-backend:
    container_name: catalog_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: catalog-database
    links:
      - catalog-database

