version: '3'

services:
  catalog-database:
    container_name: catalog_database
    image: postgres
    restart: always
#    volumes:
#      - ${RINA_PROJECT_PATH_STORAGE_DATABASE}
    networks:
      - backend-network
    environment:
      POSTGRES_USER: ${RINA_PROJECT_DATABASE_NAME}
      POSTGRES_PASSWORD: ${RINA_PROJECT_DATABASE_PASSWORD}
      POSTGRES_DB: ${RINA_PROJECT_DATABASE_NAME}

  catalog-backend:
    container_name: catalog_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-network
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: catalog-database
    links:
      - catalog-database

networks:
  backend-network:
    driver: bridge
